export {default as Home} from './Home'
export { default as About } from './About'
export {default as Product} from './products/Product'
export {default as Users} from './users/Users'
export {default as Order} from './orders/Order'